#!/usr/bin/env bash
set -euo pipefail

# One-shot setup script for server (Linux/macOS)
# Installs LibreOffice (soffice), fonts, Python venv and requirements, and optionally creates a systemd service.
# Usage:
#   sudo bash scripts/setup_server.sh      # run as root (recommended for system installs)
#   bash scripts/setup_server.sh --user    # non-root: install venv and skip system-wide packages

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REQ_FILE="$PROJECT_DIR/requirements.txt"
VENV_DIR="$PROJECT_DIR/venv"
SERVICE_NAME="some_tools"

USAGE(){
  echo "Usage: sudo bash $0 [--user] [--service enable|disable]"
  exit 1
}

MODE="root"
ENABLE_SERVICE="no"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --user) MODE="user"; shift;;
    --service) ENABLE_SERVICE="$2"; shift 2;;
    -h|--help) USAGE;;
    *) USAGE;;
  esac
done

echo "Project: $PROJECT_DIR"
echo "Mode: $MODE"

detect_os(){
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
    return
  fi
  if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    echo "$ID"
    return
  fi
  echo "unknown"
}

OS=$(detect_os)
echo "Detected OS: $OS"

install_libreoffice_ubuntu(){
  apt-get update
  apt-get install -y libreoffice libreoffice-writer libreoffice-core libreoffice-common libreoffice-headless \
    fonts-noto-cjk python3-venv python3-pip
}

install_libreoffice_centos(){
  if command -v dnf >/dev/null 2>&1; then
    dnf install -y libreoffice libreoffice-headless
  else
    yum install -y libreoffice libreoffice-headless
  fi
  # fonts vary by distro
}

install_libreoffice_macos(){
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew not found. Install Homebrew first: https://brew.sh/" >&2
    exit 1
  fi
  brew install --cask libreoffice || true
}

if [[ "$MODE" == "root" ]]; then
  case "$OS" in
    ubuntu|debian)
      echo "Installing system packages for Debian/Ubuntu..."
      install_libreoffice_ubuntu
      ;;
    centos|rhel|fedora)
      echo "Installing system packages for CentOS/RHEL/Fedora..."
      install_libreoffice_centos
      ;;
    macos)
      echo "Installing LibreOffice on macOS via Homebrew..."
      install_libreoffice_macos
      ;;
    *)
      echo "Unsupported or unknown OS: $OS. Please install LibreOffice and fonts manually." >&2
      ;;
  esac
else
  echo "User mode: skipping system package installation. Ensure LibreOffice is installed if you need soffice fallback."
fi

# Create Python venv and install requirements
echo "Creating Python venv at $VENV_DIR (if missing)"
if [[ ! -d "$VENV_DIR" ]]; then
  python3 -m venv "$VENV_DIR"
fi
"$VENV_DIR/bin/python" -m pip install --upgrade pip
if [[ -f "$REQ_FILE" ]]; then
  echo "Installing Python requirements from $REQ_FILE"
  "$VENV_DIR/bin/python" -m pip install -r "$REQ_FILE"
else
  echo "No requirements.txt found at $REQ_FILE; skipping pip install."
fi

# Ensure SOFFICE_PATH or PATH contains soffice
SOFFICE_EXEC=""
if [[ -n "${SOFFICE_PATH:-}" ]]; then
  SOFFICE_EXEC="$SOFFICE_PATH"
fi
if [[ -z "$SOFFICE_EXEC" ]]; then
  if command -v soffice >/dev/null 2>&1; then
    SOFFICE_EXEC=$(command -v soffice)
  elif command -v soffice.exe >/dev/null 2>&1; then
    SOFFICE_EXEC=$(command -v soffice.exe)
  else
    # try common paths
    for p in "/usr/bin/soffice" "/usr/local/bin/soffice" "/Applications/LibreOffice.app/Contents/MacOS/soffice"; do
      if [[ -x "$p" ]]; then
        SOFFICE_EXEC="$p"; break
      fi
    done
  fi
fi

if [[ -n "$SOFFICE_EXEC" ]]; then
  echo "Found soffice at: $SOFFICE_EXEC"
else
  echo "Warning: soffice not found in PATH nor common locations. LibreOffice may not be installed or not in PATH." >&2
fi

# Optionally write SOFFICE_PATH into /etc/profile.d so it is available system-wide (root mode)
if [[ "$MODE" == "root" && -n "$SOFFICE_EXEC" ]]; then
  echo "Exporting SOFFICE_PATH to /etc/profile.d/soffice.sh"
  cat > /etc/profile.d/soffice.sh <<EOF
# Generated by setup_server.sh
export SOFFICE_PATH="$SOFFICE_EXEC"
export PATH="${PATH}:$(dirname "$SOFFICE_EXEC")"
EOF
  chmod 644 /etc/profile.d/soffice.sh
fi

echo "Setting up run script and optional systemd unit (Linux)"
RUN_SH="$PROJECT_DIR/run.sh"
cat > "$RUN_SH" <<'EOF'
#!/usr/bin/env bash
cd "$(dirname "$0")"
if [[ -n "${SOFFICE_PATH:-}" ]]; then
  export PATH="$PATH:$(dirname "$SOFFICE_PATH")"
fi
exec "$VENV_DIR/bin/python" "$PROJECT_DIR/app.py"
EOF
chmod +x "$RUN_SH"

if [[ "$ENABLE_SERVICE" == "enable" && "$OS" != "macos" ]]; then
  SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"
  cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=$SERVICE_NAME service
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$PROJECT_DIR
Environment=SOFFICE_PATH=$SOFFICE_EXEC
ExecStart=$VENV_DIR/bin/python $PROJECT_DIR/app.py
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload || true
  systemctl enable --now "$SERVICE_NAME" || true
  echo "Systemd service installed and started: $SERVICE_NAME"
fi

echo "Setup complete. To run the app now (in this session):"
echo "  $VENV_DIR/bin/python $PROJECT_DIR/app.py"
echo "Or use the helper: $RUN_SH"
echo "If you modified system profile, open a new terminal session to pick up SOFFICE_PATH/PATH changes."

exit 0
